### ISSUE TITLE
Pymol Visualization - UnicodeDecodeError: 'utf-8' codec

### ISSUE THREAD

**Issue by frankchen121212** [jhmlam/NucleicNet#5]
Hi, Jordy

This is Siyuan from Prof Gao's group. I'm trying to reproduce the older version of NucleicNet, but I cannot find the old script. 

We've already built a database at https://arxiv.org/abs/2205.07673

I've already finished the Feature Generation and Deep Learning procedure, I think I've encountered the error  in the NucleicNet_VisualisePymol.py, thus I cannot generate the .pse file.

-rw-rw-r-- 1 chens0a g-chens0a 1.5M Oct 31 14:21 6niy_all_grids.xyz
-rw-rw-r-- 1 chens0a g-chens0a  50K Oct 31 14:21 6niy_DBScanBootstrapGrid.dict
-rw-rw-r-- 1 chens0a g-chens0a 2.0K Oct 31 14:21 6niy_dbscan_centroid_Bootstrap.xyz
-rw-rw-r-- 1 chens0a g-chens0a  59K Oct 31 14:26 6niy.pdb
-rw-rw-r-- 1 chens0a g-chens0a 116K Oct 31 14:23 6niy_strong_Bootstrap.pdb
-rw-rw-r-- 1 chens0a g-chens0a  71K Oct 31 14:21 6niy_strong_Bootstrap.xyz
-rw-rw-r-- 1 chens0a g-chens0a 1.7K Oct 31 14:26 6niy_temp.pml

PyMOL>save 5axw_pymol.pse
 Save: Please wait -- writing session file...
 ExecutiveGetSession: a Python error occured during creation of the session object:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 2: invalid continuation byte

Do you know how to solve this problem? Hope that you can help. Thank you!

You can always find me at siyuan.chen@kaust.edu.sa

**Comment by jhmlam** [comment]
Hi Siyuan,

We have migrated to pymol > 2.4 and I am using pymol 2.5.1, which pymol you are using? 
The current version is stable, where @JoshuaChou2018 next door can also use it. @JoshuaChou2018 can you help Siyuan to set up the pymol?
Sorry for the delay in reply. 

Best,
Jordy

**Comment by frankchen121212** [comment]
Thank you for your reply, I‘m currently using PYMOL 2.3.5', I'll upgrade to 2.5.1 to see if it solves the problem.

**Comment by jhmlam** [comment]
@frankchen121212 Great. Also, if you really need the very old version which I cannot support anymore, you can find it at https://github.com/jhmlam/NucleicNet/blob/fca09d38b9a70d2c402414df7cc06b9dd2824449/Script/NucleicNet_VisualisePymol.py 
Cheers.

**Comment by frankchen121212** [comment]
Really Appreciated it, thank you!
